apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: my-first-openshift-service-a
build:
  artifacts:
  - image: localhost:5000/service-a
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k3s.yaml
