controller:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    hostName: jenkins.rancher.localhost
  installPlugins:
  - kubernetes:latest
  - workflow-aggregator:latest
  - git:latest
  - configuration-as-code:latest
  - blueocean:latest
