apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
  - name: kustomize
    image: nekottyo/kustomize-kubeval
    command:
    - cat
    tty: true
