##################################################################################################
# Local registry
##################################################################################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-registry
  labels:
    name: ingress-registry
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: registry.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: registry
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: registry
  labels:
    app: registry
    service: registry
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
